### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by cherrybeard** [cherrybeard/raf-please#2]
### React:
- [x] Rename cafe → place
- [x] Unify mentions rendering
- [x] Split storage to separate files for places and cities
- [x] Split every place into separate json file
- [x] Split place content rendering into separate modules
- [x] Split data from code
- [ ] Get rid of relative paths in import modules
- [ ] Get rid of relative paths in require images
- [ ] Change logo to be link or not 
- [ ] SEO images alt 
- [ ] List to paragraphs function

### Styles:
- [x] Remove cursor: pointer on links
- [x] Make section and section-content pseudoclasses
- [x] Fix place cover image a-la 500px 
- [ ] Make sure place-preview classes are not just place- but place-preview-

### Features:
- [ ] Read-more suggestions
- [ ] New and lovelove badges

**Comment by cherrybeard** [comment]
Now:

- [x] Get rid of relative paths in import modules
- [x] Fix place cover image a-la 500px
- [x] Read-more suggestions
- [ ] Adaptivity
- [ ] Endorphin page
- [ ] Pitchii change one photo
- [ ] Alt for images
- [ ] List of cities
- [ ] List to paragraphs function
